//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientsAllergies
    {
        public int Id { get; set; }
        public Nullable<int> AllergyId { get; set; }
        public Nullable<int> PatientId { get; set; }
    
        public virtual Allergies Allergies { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
